# Generated by Django 2.2.2 on 2019-12-23 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
                ('task', models.CharField(max_length=80, null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('username', models.CharField(max_length=80, null=True)),
                ('user_image', models.ImageField(default='image/photo.png', upload_to='media/image/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('event_id', models.CharField(max_length=120, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('event_type', models.IntegerField()),
                ('PreparingHours', models.IntegerField(default=0)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
